version: "3.9"
services:
  webserver:
    container_name: PHP-webserver
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html
    ports:
      - 8123:80
    depends_on:
      - mysql-db

  mysql-db:
    image: dockerhub.timeweb.cloud/mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_database
      MYSQL_USER: db_user
      MYSQL_PASSWORD: ukHLIUFNYiulgyi4h
    ports:
      - "3306:3306"
